### PR TITLE
Updating README

### PR DESCRIPTION
**Pull request by mtouzot**
To follow the [documentation](https://www.raspberrypi.com/documentation/computers/camera_software.html#building-libcamera-and-rpicam-apps), I've adapted the README to build `libcamera` on Raspberry Pi.

### CODE REVIEW

**Comment by naushir** [comment]
Thank you for creating this PR.  Unfortunately we will probably not merge this as the README file is an upstream libcamera file and we are trying to avoid diverging as much as we can.  There was a similar PR closed for the same reason: https://github.com/raspberrypi/libcamera/pull/55.

The official instructions are always going to be available on our [documentation](https://www.raspberrypi.com/documentation/computers/camera_software.html#libcamera-and-libcamera-apps-packages) website:

**Comment by naushir** [comment]
Having said that, perhaps this README can be updated as an exception now...  @davidplowman what do you think?

**Comment by unitydevelopers-greg** [comment]
@naushir @davidplowman highly recommend merging this PR. It will save a lot of research to Pi users

**Comment by mtouzot** [comment]
Thanks for merging.

@unitydevelopers-greg After doing two installations months apart without remembering how to do it, I hope this will save time for other users.

**Pull request merged**
