### PR TITLE
16-bit endian swap + Black level fixes

### PR DESCRIPTION
**Pull request by naushir**

### CODE REVIEW

**Comment by naushir** [comment]
@davidplowman can you check the black level commit logic and see if you think it makes sense?

**Comment by davidplowman** [comment]
Things have swapped round a bit, but I think it looks OK. I take it there's no attempt (yet?) to set the FE black level to zero (so that it does nothing) but allow a non-zero black level in the BE?

**Comment by naushir** [comment]
> I take it there's no attempt (yet?) to set the FE black level to zero (so that it does nothing) but allow a non-zero black level in the BE?

No, that's something we do want to add, but I left this change pisp specific for now.  The separating out the BL in FE/BE will need an algorithm change that probably wants to go through the mailing list?

**Comment by naushir** [comment]
Now merged manually.

**Pull request closed without merging**
